In [1]:
import numpy as np

In [2]:
M = np.array([[1,2,3],
              [4,5,6]])
print(M.shape)

(2, 3)


In [3]:
# Create a 2D NumPy array with 3 rows and 2 columns, filled with pi
N = np.full((3,2), np.pi) # Mmm pies.. 🥧
print(N)

[[3.14159265 3.14159265]
 [3.14159265 3.14159265]
 [3.14159265 3.14159265]]


In [4]:
# full will let values be lists
# this will create a 3x3 array with 1, 2, 3 across each row
one_two_three = np.full((3, 3), [1, 2, 3])
print(one_two_three)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [5]:
# Create the identity matrix of size 4:
I = np.eye(4) # we'll use this again when we get to matrices.. esp. bigger ones
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
I.ndim

2

In [7]:
M.shape

(2, 3)

In [8]:
M.size

6

In [9]:
v = np.array([1,2,3])
w = np.array([1,0,-1])

In [10]:
v + w

array([2, 2, 2])

In [11]:
v - w

array([0, 2, 4])

In [12]:
2*v

array([2, 4, 6])

In [13]:
w / 2

array([ 0.5,  0. , -0.5])

In [14]:
v ** 2

array([1, 4, 9])

In [15]:
a = np.array( [[1,2,3],
               [4,5,6],
               [7,8,9]])

b = np.array( [[3,1,4],
               [1,5,9],
               [2,6,5]])

print(2*a + b)

[[ 5  5 10]
 [ 9 15 21]
 [16 22 23]]


In [16]:
a*b # NOT WHAT I WANTED...

array([[ 3,  2, 12],
       [ 4, 25, 54],
       [14, 48, 45]])

In [17]:
a@b # ah, that's matrix multiplication

array([[ 11,  29,  37],
       [ 29,  65,  91],
       [ 47, 101, 145]])

In [18]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
np.trace(a)

15

In [20]:
# Even though we already imported numpy, we can save some keystrokes
# by giving it a shortcut name
import numpy.linalg as la

la.det(b)

-90.0

In [21]:
la.inv(b)

array([[ 0.32222222, -0.21111111,  0.12222222],
       [-0.14444444, -0.07777778,  0.25555556],
       [ 0.04444444,  0.17777778, -0.15555556]])

In [22]:
# Check b multiplied by inverse
b@la.inv(b)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -1.38777878e-16],
       [ 5.55111512e-17, -1.38777878e-16,  1.00000000e+00]])

In [23]:
la.inv(b)@b

array([[ 1.00000000e+00,  8.32667268e-17,  2.91433544e-16],
       [ 0.00000000e+00,  1.00000000e+00, -1.66533454e-16],
       [-5.55111512e-17, -1.66533454e-16,  1.00000000e+00]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
a = np.array([[1, 2],
             [3, 5]])
b = np.array([1,2])

np.linalg.solve(a, b)

array([-1.,  1.])